default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/plan_to_meet_development

test:
  <<: *default
  database: db/plan_to_meet_test

production:
  <<: *default
  database: db/plan_to_meet_production
